In [59]:
import torch
from torch.utils.data import DataLoader
from torchvision import transforms
from PIL import Image

from dataset.vqa_dataset import vqa_dataset
# from dataset.grounding_dataset import grounding_dataset

from dataset.randaugment import RandomAugment
from utils import MetricLogger
from dataset import create_dataset, create_sampler, create_loader, vqa_collate_fn,vqa_dataset

normalize = transforms.Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711))
    
train_transform = transforms.Compose([                        
            transforms.RandomResizedCrop(384,scale=(0.5, 1.0), interpolation=Image.BICUBIC),
            transforms.RandomHorizontalFlip(),
            RandomAugment(2,7,isPIL=True,augs=['Identity','AutoContrast','Equalize','Brightness','Sharpness',
                                              'ShearX', 'ShearY', 'TranslateX', 'TranslateY', 'Rotate']),     
            transforms.ToTensor(),
            normalize,
        ])  

vqa_test_dataset = vqa_dataset(['/home/xinghao/code/datasets/vqa2/vqa_train.json'], train_transform, '/home/xinghao/code/datasets/vqa2', '', split='train') 
print(vqa_test_dataset.__getitem__(1))
train_loader = create_loader((vqa_test_dataset,),[None],
                                              batch_size=[3],
                                              num_workers=[4],is_trains=[True], 
                                              collate_fns=[vqa_collate_fn])

metric_logger = MetricLogger(delimiter="  ")

# for i,(image, question, answer, weights, n) in enumerate(train_loader[0]):
#     print(image, question, answer, weights, n)

/home/xinghao/anaconda3/envs/xinghao/lib/python3.10/site-packages/torchvision/transforms/transforms.py:891: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(


(tensor([[[ 1.9303,  1.9303,  1.9303,  ...,  1.8719,  1.4632,  1.5216],
         [ 1.9303,  1.9303,  1.9303,  ...,  1.7990,  1.6092,  1.6968],
         [ 1.8573,  1.9303,  1.9303,  ...,  1.8135,  1.8573,  1.9157],
         ...,
         [-0.4346, -0.3762, -0.1864,  ..., -0.6098, -0.7412, -0.6828],
         [-0.4346, -0.3762, -0.2448,  ..., -0.7850, -0.6682, -0.3470],
         [-0.6536, -0.5076, -0.1864,  ..., -0.6536, -0.4638, -0.2886]],

        [[ 1.6247,  1.5646,  1.6697,  ...,  1.5046,  1.0844,  1.1444],
         [ 1.5046,  1.5196,  1.5946,  ...,  1.4446,  1.2645,  1.3395],
         [ 1.4295,  1.5046,  1.6096,  ...,  1.4295,  1.4896,  1.5196],
         ...,
         [-0.3714, -0.2663, -0.0712,  ..., -0.5815, -0.7016, -0.5815],
         [-0.3564, -0.2663, -0.0412,  ..., -0.8216, -0.6715, -0.2213],
         [-0.5365, -0.3864,  0.0789,  ..., -0.6565, -0.4164, -0.1012]],

        [[ 1.0510,  1.0083,  1.0510,  ...,  1.0083,  0.6244,  0.6812],
         [ 1.0652,  1.0794,  1.0083,  ...,  

tensor([1., 2.])
tensor([3.])
